name: hello-world
on: push
jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"

name: Build App
on: push
jobs: 

# BUILD APP

  build:
    runs-on: ubuntu-latest
    steps: 
     - name: Checkout Code
       uses: actions/checkout@v3
     - name: Install Node
       uses: actions/setup-node@v3
       with:
         node-version: 21.x
     - name: Install Dependencies
       run: npm install
     - name: Build Project
       run: npm run build
     - name: Upload artifact to enable deployment
       uses: actions/upload-artifact@v3
       with:
         name: production-files
         path: ./dist

# DEPLOY APP

  deploy:
    # Add a dependency to the build job
    needs: build
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ci_cd_react }}
          publish_dir: ./dist
